
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["1020 1025 1", "1020 1025 2", "1020 1025 3", "1020 1025 4", "1020 1025 5", "1020 1025 6", "1020 1025 7", "1020 1025 8", "1020 1025 9", "1020 1025 10", "1025 1030 11", "1025 1030 12", "1025 1030 13", "1025 1030 14", "1025 1030 15", "1025 1030 16", "1025 1030 17", "1025 1030 18", "1025 1030 19", "1025 1030 20", "1030 1035 21", "1030 1035 22", "1030 1035 23", "1030 1035 24", "1030 1035 25", "1030 1035 26", "1030 1035 27", "1030 1035 28", "1030 1035 29", "1030 1035 30", "1035 1040 31", "1035 1040 32", "1035 1040 33", "1035 1040 34", "1035 1040 35", "1035 1040 36", "1035 1040 37", "1035 1040 38", "1035 1040 39", "1035 1040 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
