
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["1060 1065 1", "1060 1065 2", "1060 1065 3", "1060 1065 4", "1060 1065 5", "1060 1065 6", "1060 1065 7", "1060 1065 8", "1060 1065 9", "1060 1065 10", "1065 1070 11", "1065 1070 12", "1065 1070 13", "1065 1070 14", "1065 1070 15", "1065 1070 16", "1065 1070 17", "1065 1070 18", "1065 1070 19", "1065 1070 20", "1070 1075 21", "1070 1075 22", "1070 1075 23", "1070 1075 24", "1070 1075 25", "1070 1075 26", "1070 1075 27", "1070 1075 28", "1070 1075 29", "1070 1075 30", "1075 1080 31", "1075 1080 32", "1075 1080 33", "1075 1080 34", "1075 1080 35", "1075 1080 36", "1075 1080 37", "1075 1080 38", "1075 1080 39", "1075 1080 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
