
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["1040 1045 1", "1040 1045 2", "1040 1045 3", "1040 1045 4", "1040 1045 5", "1040 1045 6", "1040 1045 7", "1040 1045 8", "1040 1045 9", "1040 1045 10", "1045 1050 11", "1045 1050 12", "1045 1050 13", "1045 1050 14", "1045 1050 15", "1045 1050 16", "1045 1050 17", "1045 1050 18", "1045 1050 19", "1045 1050 20", "1050 1055 21", "1050 1055 22", "1050 1055 23", "1050 1055 24", "1050 1055 25", "1050 1055 26", "1050 1055 27", "1050 1055 28", "1050 1055 29", "1050 1055 30", "1055 1060 31", "1055 1060 32", "1055 1060 33", "1055 1060 34", "1055 1060 35", "1055 1060 36", "1055 1060 37", "1055 1060 38", "1055 1060 39", "1055 1060 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
