
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["100 105 1", "100 105 2", "100 105 3", "100 105 4", "100 105 5", "100 105 6", "100 105 7", "100 105 8", "100 105 9", "100 105 10", "105 110 11", "105 110 12", "105 110 13", "105 110 14", "105 110 15", "105 110 16", "105 110 17", "105 110 18", "105 110 19", "105 110 20", "110 115 21", "110 115 22", "110 115 23", "110 115 24", "110 115 25", "110 115 26", "110 115 27", "110 115 28", "110 115 29", "110 115 30", "115 120 31", "115 120 32", "115 120 33", "115 120 34", "115 120 35", "115 120 36", "115 120 37", "115 120 38", "115 120 39", "115 120 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
